### ISSUE TITLE
Is it possible for you to test?

### ISSUE THREAD

**Issue by JafferWilson** [meyersbs/personality#1]
Just for the confirmation the datasets what exactly we will need for the training and how the trained will offer result. Kindly let me know.

**Comment by meyersbs** [comment]
@JafferWilson, I'm not certain what exactly you're looking for. Also, please be aware, that this is not a high priority project for me.

**Comment by JafferWilson** [comment]
Thank you for your reply.

**Comment by mgene123** [comment]
how run this project

**Comment by mgene123** [comment]
@JafferWilson how run this project

**Comment by meyersbs** [comment]
@mgene123 Run `python3 main.py --help` to see the available commands. Please note that this project is in very early development.
